# Generated by Django 5.1.6 on 2025-02-05 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='dia_semana',
            field=models.IntegerField(blank=True, choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='recurrente',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
